// <auto-generated />
using System;
using MecaniCar360.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MecaniCar360.Migrations
{
    [DbContext(typeof(MecaniCarContext))]
    partial class MecaniCarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MecaniCar360.Models.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("MecaniCar360.Models.CalificacionTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("OrdenTrabajoId")
                        .HasColumnType("int");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("OrdenTrabajoId")
                        .IsUnique();

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("MecaniCar360.Models.Diagnostico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionActual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaUltimaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("OrdenTrabajoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenTrabajoId");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("MecaniCar360.Models.DiagnosticoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiagnosticoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("MecanicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticoId");

                    b.HasIndex("MecanicoId");

                    b.ToTable("DiagnosticoHistoriales");
                });

            modelBuilder.Entity("MecaniCar360.Models.DominioVehicular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaDesde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("DominiosVehiculares");
                });

            modelBuilder.Entity("MecaniCar360.Models.EvidenciaTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("OrdenTrabajoId")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SubidaPorUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenTrabajoId");

                    b.HasIndex("SubidaPorUsuarioId");

                    b.ToTable("Evidencias");
                });

            modelBuilder.Entity("MecaniCar360.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("LinkPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdenTrabajoId")
                        .HasColumnType("int");

                    b.Property<int?>("PresupuestoOrigenId")
                        .HasColumnType("int");

                    b.Property<string>("QRPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroFactura")
                        .IsUnique();

                    b.HasIndex("OrdenTrabajoId")
                        .IsUnique();

                    b.HasIndex("PresupuestoOrigenId");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("MecaniCar360.Models.FacturaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("FacturaItems");
                });

            modelBuilder.Entity("MecaniCar360.Models.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("FamiliaPadreId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaPadreId");

                    b.ToTable("Familias");
                });

            modelBuilder.Entity("MecaniCar360.Models.FamiliaPatente", b =>
                {
                    b.Property<int>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<int>("PatenteId")
                        .HasColumnType("int");

                    b.HasKey("FamiliaId", "PatenteId");

                    b.HasIndex("PatenteId");

                    b.ToTable("FamiliaPatentes");
                });

            modelBuilder.Entity("MecaniCar360.Models.Garantia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("CreadaPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrdenTrabajoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreadaPorUsuarioId");

                    b.HasIndex("OrdenTrabajoId")
                        .IsUnique();

                    b.ToTable("Garantias");
                });

            modelBuilder.Entity("MecaniCar360.Models.GarantiaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GarantiaId")
                        .HasColumnType("int");

                    b.Property<int>("MesesGarantia")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PresupuestoItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GarantiaId");

                    b.HasIndex("PresupuestoItemId");

                    b.ToTable("GarantiaItems");
                });

            modelBuilder.Entity("MecaniCar360.Models.IngresoVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ClienteEspera")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaEgreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ObservacionesRecepcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TurnoId")
                        .IsUnique();

                    b.ToTable("IngresosVehiculo");
                });

            modelBuilder.Entity("MecaniCar360.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("MecaniCar360.Models.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId", "Nombre")
                        .IsUnique();

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("MecaniCar360.Models.MovimientoStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OrdenTrabajoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProveedorRepuestoId")
                        .HasColumnType("int");

                    b.Property<int>("RealizadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RepuestoId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenTrabajoId");

                    b.HasIndex("ProveedorRepuestoId");

                    b.HasIndex("RealizadoPorUsuarioId");

                    b.HasIndex("RepuestoId");

                    b.ToTable("MovimientosStock");
                });

            modelBuilder.Entity("MecaniCar360.Models.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("MecaniCar360.Models.OrdenTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CostoDiagnostico")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CreadaPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoActual")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HorasEstimadas")
                        .HasColumnType("int");

                    b.Property<int?>("HorasReales")
                        .HasColumnType("int");

                    b.Property<int>("IngresoVehiculoId")
                        .HasColumnType("int");

                    b.Property<int?>("MecanicoId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Urgencia")
                        .HasColumnType("int");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreadaPorUsuarioId");

                    b.HasIndex("IngresoVehiculoId")
                        .IsUnique();

                    b.HasIndex("MecanicoId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("OrdenesTrabajo");
                });

            modelBuilder.Entity("MecaniCar360.Models.OrdenTrabajoEstadoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("MecanicoId")
                        .HasColumnType("int");

                    b.Property<int>("OrdenTrabajoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MecanicoId");

                    b.HasIndex("OrdenTrabajoId");

                    b.ToTable("OrdenTrabajoEstados");
                });

            modelBuilder.Entity("MecaniCar360.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RegistradoPorUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("RegistradoPorUsuarioId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("MecaniCar360.Models.Patente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Patentes");
                });

            modelBuilder.Entity("MecaniCar360.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("MecaniCar360.Models.PersonaRol", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OtorgadoPorUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("PersonaId", "RolId");

                    b.HasIndex("OtorgadoPorUsuarioId");

                    b.HasIndex("RolId");

                    b.ToTable("PersonaRoles");
                });

            modelBuilder.Entity("MecaniCar360.Models.Presupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaUltimaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("MecanicoId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdenTrabajoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MecanicoId");

                    b.HasIndex("OrdenTrabajoId")
                        .IsUnique();

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("MecaniCar360.Models.PresupuestoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("MecanicoId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PresupuestoId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAnterior")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MecanicoId");

                    b.HasIndex("PresupuestoId");

                    b.ToTable("PresupuestoHistoriales");
                });

            modelBuilder.Entity("MecaniCar360.Models.PresupuestoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PresupuestoId")
                        .HasColumnType("int");

                    b.Property<int?>("RepuestoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PresupuestoId");

                    b.HasIndex("RepuestoId");

                    b.ToTable("PresupuestoItems");
                });

            modelBuilder.Entity("MecaniCar360.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("MecaniCar360.Models.ProveedorRepuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoProveedor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PrecioCompraActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("RepuestoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RepuestoId");

                    b.HasIndex("ProveedorId", "RepuestoId")
                        .IsUnique();

                    b.ToTable("ProveedorRepuestos");
                });

            modelBuilder.Entity("MecaniCar360.Models.Repuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Compatibilidad")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Repuestos");
                });

            modelBuilder.Entity("MecaniCar360.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("EsRolCliente")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MecaniCar360.Models.RolFamilia", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("int");

                    b.HasKey("RolId", "FamiliaId");

                    b.HasIndex("FamiliaId");

                    b.ToTable("RolFamilias");
                });

            modelBuilder.Entity("MecaniCar360.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("CreadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("MecaniCar360.Models.TurnoEstadoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TurnoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TurnoEstados");
                });

            modelBuilder.Entity("MecaniCar360.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("EmailLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<bool>("PrimerLogin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TokenRecuperacionExpira")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenRecuperacionPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmailLogin")
                        .IsUnique();

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MecaniCar360.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("Kilometraje")
                        .HasColumnType("int");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int");

                    b.Property<string>("Motor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ModeloId");

                    b.HasIndex("Patente")
                        .IsUnique();

                    b.HasIndex("Vin")
                        .IsUnique()
                        .HasFilter("[Vin] IS NOT NULL");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("MecaniCar360.Models.Auditoria", b =>
                {
                    b.HasOne("MecaniCar360.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MecaniCar360.Models.CalificacionTrabajo", b =>
                {
                    b.HasOne("MecaniCar360.Models.Persona", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.OrdenTrabajo", "OrdenTrabajo")
                        .WithOne("Calificacion")
                        .HasForeignKey("MecaniCar360.Models.CalificacionTrabajo", "OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("MecaniCar360.Models.Diagnostico", b =>
                {
                    b.HasOne("MecaniCar360.Models.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("MecaniCar360.Models.DiagnosticoHistorial", b =>
                {
                    b.HasOne("MecaniCar360.Models.Diagnostico", "Diagnostico")
                        .WithMany("Historial")
                        .HasForeignKey("DiagnosticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.Persona", "Mecanico")
                        .WithMany()
                        .HasForeignKey("MecanicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Diagnostico");

                    b.Navigation("Mecanico");
                });

            modelBuilder.Entity("MecaniCar360.Models.DominioVehicular", b =>
                {
                    b.HasOne("MecaniCar360.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.Vehiculo", "Vehiculo")
                        .WithMany("DominiosVehiculares")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("MecaniCar360.Models.EvidenciaTrabajo", b =>
                {
                    b.HasOne("MecaniCar360.Models.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Evidencias")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.Usuario", "SubidaPorUsuario")
                        .WithMany()
                        .HasForeignKey("SubidaPorUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("SubidaPorUsuario");
                });

            modelBuilder.Entity("MecaniCar360.Models.Factura", b =>
                {
                    b.HasOne("MecaniCar360.Models.OrdenTrabajo", "OrdenTrabajo")
                        .WithOne("Factura")
                        .HasForeignKey("MecaniCar360.Models.Factura", "OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.Presupuesto", "PresupuestoOrigen")
                        .WithMany()
                        .HasForeignKey("PresupuestoOrigenId");

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("PresupuestoOrigen");
                });

            modelBuilder.Entity("MecaniCar360.Models.FacturaItem", b =>
                {
                    b.HasOne("MecaniCar360.Models.Factura", "Factura")
                        .WithMany("Items")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("MecaniCar360.Models.Familia", b =>
                {
                    b.HasOne("MecaniCar360.Models.Familia", "FamiliaPadre")
                        .WithMany("FamiliasHijas")
                        .HasForeignKey("FamiliaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FamiliaPadre");
                });

            modelBuilder.Entity("MecaniCar360.Models.FamiliaPatente", b =>
                {
                    b.HasOne("MecaniCar360.Models.Familia", "Familia")
                        .WithMany("Patentes")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.Patente", "Patente")
                        .WithMany("Familias")
                        .HasForeignKey("PatenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Familia");

                    b.Navigation("Patente");
                });

            modelBuilder.Entity("MecaniCar360.Models.Garantia", b =>
                {
                    b.HasOne("MecaniCar360.Models.Usuario", "CreadaPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadaPorUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.OrdenTrabajo", "OrdenTrabajo")
                        .WithOne("Garantia")
                        .HasForeignKey("MecaniCar360.Models.Garantia", "OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreadaPorUsuario");

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("MecaniCar360.Models.GarantiaItem", b =>
                {
                    b.HasOne("MecaniCar360.Models.Garantia", "Garantia")
                        .WithMany("Items")
                        .HasForeignKey("GarantiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.PresupuestoItem", "PresupuestoItem")
                        .WithMany()
                        .HasForeignKey("PresupuestoItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Garantia");

                    b.Navigation("PresupuestoItem");
                });

            modelBuilder.Entity("MecaniCar360.Models.IngresoVehiculo", b =>
                {
                    b.HasOne("MecaniCar360.Models.Turno", "Turno")
                        .WithOne("IngresoVehiculo")
                        .HasForeignKey("MecaniCar360.Models.IngresoVehiculo", "TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("MecaniCar360.Models.Modelo", b =>
                {
                    b.HasOne("MecaniCar360.Models.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("MecaniCar360.Models.MovimientoStock", b =>
                {
                    b.HasOne("MecaniCar360.Models.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany()
                        .HasForeignKey("OrdenTrabajoId");

                    b.HasOne("MecaniCar360.Models.ProveedorRepuesto", "ProveedorRepuesto")
                        .WithMany()
                        .HasForeignKey("ProveedorRepuestoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MecaniCar360.Models.Usuario", "RealizadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("RealizadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.Repuesto", "Repuesto")
                        .WithMany("Movimientos")
                        .HasForeignKey("RepuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("ProveedorRepuesto");

                    b.Navigation("RealizadoPorUsuario");

                    b.Navigation("Repuesto");
                });

            modelBuilder.Entity("MecaniCar360.Models.Notificacion", b =>
                {
                    b.HasOne("MecaniCar360.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("MecaniCar360.Models.OrdenTrabajo", b =>
                {
                    b.HasOne("MecaniCar360.Models.Usuario", "CreadaPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadaPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.IngresoVehiculo", "IngresoVehiculo")
                        .WithOne("OrdenTrabajo")
                        .HasForeignKey("MecaniCar360.Models.OrdenTrabajo", "IngresoVehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.Persona", "Mecanico")
                        .WithMany()
                        .HasForeignKey("MecanicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MecaniCar360.Models.Vehiculo", null)
                        .WithMany("OrdenesTrabajo")
                        .HasForeignKey("VehiculoId");

                    b.Navigation("CreadaPorUsuario");

                    b.Navigation("IngresoVehiculo");

                    b.Navigation("Mecanico");
                });

            modelBuilder.Entity("MecaniCar360.Models.OrdenTrabajoEstadoHistorial", b =>
                {
                    b.HasOne("MecaniCar360.Models.Persona", "Mecanico")
                        .WithMany()
                        .HasForeignKey("MecanicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MecaniCar360.Models.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mecanico");

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("MecaniCar360.Models.Pago", b =>
                {
                    b.HasOne("MecaniCar360.Models.Factura", "Factura")
                        .WithMany("Pagos")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.Usuario", "RegistradoPorUsuario")
                        .WithMany()
                        .HasForeignKey("RegistradoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("RegistradoPorUsuario");
                });

            modelBuilder.Entity("MecaniCar360.Models.PersonaRol", b =>
                {
                    b.HasOne("MecaniCar360.Models.Usuario", "OtorgadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("OtorgadoPorUsuarioId");

                    b.HasOne("MecaniCar360.Models.Persona", "Persona")
                        .WithMany("Roles")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.Rol", "Rol")
                        .WithMany("Personas")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OtorgadoPorUsuario");

                    b.Navigation("Persona");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MecaniCar360.Models.Presupuesto", b =>
                {
                    b.HasOne("MecaniCar360.Models.Persona", "Mecanico")
                        .WithMany()
                        .HasForeignKey("MecanicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MecaniCar360.Models.OrdenTrabajo", "OrdenTrabajo")
                        .WithOne("Presupuesto")
                        .HasForeignKey("MecaniCar360.Models.Presupuesto", "OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mecanico");

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("MecaniCar360.Models.PresupuestoHistorial", b =>
                {
                    b.HasOne("MecaniCar360.Models.Persona", "Mecanico")
                        .WithMany()
                        .HasForeignKey("MecanicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.Presupuesto", "Presupuesto")
                        .WithMany("Historial")
                        .HasForeignKey("PresupuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mecanico");

                    b.Navigation("Presupuesto");
                });

            modelBuilder.Entity("MecaniCar360.Models.PresupuestoItem", b =>
                {
                    b.HasOne("MecaniCar360.Models.Presupuesto", "Presupuesto")
                        .WithMany("Items")
                        .HasForeignKey("PresupuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.Repuesto", "Repuesto")
                        .WithMany("PresupuestoItems")
                        .HasForeignKey("RepuestoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Presupuesto");

                    b.Navigation("Repuesto");
                });

            modelBuilder.Entity("MecaniCar360.Models.ProveedorRepuesto", b =>
                {
                    b.HasOne("MecaniCar360.Models.Proveedor", "Proveedor")
                        .WithMany("Repuestos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.Repuesto", "Repuesto")
                        .WithMany("Proveedores")
                        .HasForeignKey("RepuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Repuesto");
                });

            modelBuilder.Entity("MecaniCar360.Models.RolFamilia", b =>
                {
                    b.HasOne("MecaniCar360.Models.Familia", "Familia")
                        .WithMany("Roles")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.Rol", "Rol")
                        .WithMany("Familias")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Familia");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MecaniCar360.Models.Turno", b =>
                {
                    b.HasOne("MecaniCar360.Models.Persona", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.Usuario", "CreadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.Vehiculo", "Vehiculo")
                        .WithMany("Turnos")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("MecaniCar360.Models.TurnoEstadoHistorial", b =>
                {
                    b.HasOne("MecaniCar360.Models.Turno", "Turno")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Turno");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MecaniCar360.Models.Usuario", b =>
                {
                    b.HasOne("MecaniCar360.Models.Persona", "Persona")
                        .WithOne("Usuario")
                        .HasForeignKey("MecaniCar360.Models.Usuario", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("MecaniCar360.Models.Vehiculo", b =>
                {
                    b.HasOne("MecaniCar360.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MecaniCar360.Models.Modelo", "Modelo")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marca");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("MecaniCar360.Models.Diagnostico", b =>
                {
                    b.Navigation("Historial");
                });

            modelBuilder.Entity("MecaniCar360.Models.Factura", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("MecaniCar360.Models.Familia", b =>
                {
                    b.Navigation("FamiliasHijas");

                    b.Navigation("Patentes");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("MecaniCar360.Models.Garantia", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MecaniCar360.Models.IngresoVehiculo", b =>
                {
                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("MecaniCar360.Models.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("MecaniCar360.Models.Modelo", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("MecaniCar360.Models.OrdenTrabajo", b =>
                {
                    b.Navigation("Calificacion");

                    b.Navigation("Diagnosticos");

                    b.Navigation("Evidencias");

                    b.Navigation("Factura");

                    b.Navigation("Garantia");

                    b.Navigation("HistorialEstados");

                    b.Navigation("Presupuesto");
                });

            modelBuilder.Entity("MecaniCar360.Models.Patente", b =>
                {
                    b.Navigation("Familias");
                });

            modelBuilder.Entity("MecaniCar360.Models.Persona", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MecaniCar360.Models.Presupuesto", b =>
                {
                    b.Navigation("Historial");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("MecaniCar360.Models.Proveedor", b =>
                {
                    b.Navigation("Repuestos");
                });

            modelBuilder.Entity("MecaniCar360.Models.Repuesto", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("PresupuestoItems");

                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("MecaniCar360.Models.Rol", b =>
                {
                    b.Navigation("Familias");

                    b.Navigation("Personas");
                });

            modelBuilder.Entity("MecaniCar360.Models.Turno", b =>
                {
                    b.Navigation("HistorialEstados");

                    b.Navigation("IngresoVehiculo");
                });

            modelBuilder.Entity("MecaniCar360.Models.Vehiculo", b =>
                {
                    b.Navigation("DominiosVehiculares");

                    b.Navigation("OrdenesTrabajo");

                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
